import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter=Inter({subsets:["latin"]});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
      {children}</body>
    </html>
    </ClerkProvider>
  );
}
